steps:
# Step 1: Build the application using Maven
- name: 'maven:3.8.4-openjdk-17'
  entrypoint: 'bash'
  args: ['-c', 'mvn clean package -DskipTests']

# Step 2: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-test', '.']

# Step 3: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcp-test']

# Step 4: Deploy the application to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  secretEnv: ['SECRET_SERVICENAME']
  args: [
    'run', 'deploy', 'gcp-test', 
    '--image', 'gcr.io/$PROJECT_ID/gcp-test', 
    '--platform', 'managed', 
    '--region', 'us-central1', 
    '--allow-unauthenticated',
    '--set-env-vars', 'SERVICE_NAME=$$SECRET_SERVICENAME',
     '-c',
    'echo "Secret Value: $SECRET_SERVICENAME"'
  ]


images:
- 'gcr.io/$PROJECT_ID/gcp-test'

availableSecrets:
  secretManager:
  - versionName: projects/1026963246587/secrets/SERVICENAME/versions/latest
    env: 'SECRET_SERVICENAME'
